### ISSUE TITLE
Computational time

### ISSUE THREAD

**Issue by Naxter** [PramuPerera/In2I#1]
Hey guys, 
you wrote a great paper that tackles an important and interesting field of machine learning and GANs. I would like to ask you one question: 

What is the computational effort for inference? So how long does it take to translate two input images to one resulting output image?

Thank you in advance! Keep up the good work. 

Best, 
Tobi

**Comment by mahdiabavisani** [comment]
Hi Tobi,

Thanks and sorry for the late response. Once the networks are trained, the computational complexity for transferring the input images to the target domain is only the time complexity for one forward pass of the networks.   The run time can differ depending on the hardware or the architecture of the backbone network that is used.   The complexity in terms of the number of flops can be found by using _tfprof_ in tensorflow.

tfprof:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tfprof

Best,
Mahdi
